FROM golang:1.23.6-alpine AS builder
WORKDIR /app
RUN apk add --no-cache make
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN make build-app

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin .
EXPOSE 8080
CMD ["./app-proxy"]