FROM golang:1.23.2-alpine AS builder
WORKDIR /app
RUN apk add --no-cache make
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN make build-backoffice

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin .
EXPOSE 3002
CMD ["./backoffice-proxy"]